/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.datosBasicos.cajeros;

import controlador.Coordinador;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.vo.datosBasicos.CajeroVO;
import utilidades.Formulario;
import vista.datosBasicos.ForcedListSelectionModel;

/**
 *
 * @author Victor Del Rio Prens
 */
public class Cajeros extends javax.swing.JFrame {
    private final String noHayCajeros = "Actualmente no existen cajeros dentro de la base de datos.";
    private final String ningunCajeroSeleccionado = "Por favor seleccione un cajero.";
    private final String cajeroEliminado = "El cajero fue eliminado con exito.";
    private final String cajeroNoEliminado = "Existe un problema al tratar de eliminar el cajero.";
    private final String confirmacionEliminar = "¿Desea eliminar este cajero?";
    Coordinador coordinador;
    DefaultTableModel model;
    /**
     * Creates new form Cajeros
     */
    public Cajeros() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tablaCajeros.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tablaCajeros.setDefaultRenderer(String.class, centerRenderer);
        tablaCajeros.setDefaultRenderer(Integer.class, centerRenderer);
        tablaCajeros.setSelectionModel(new ForcedListSelectionModel());
    }

    /**
     * Permite crear una fila dentro de la tabla
     * @param codigo
     * @param nombre
     * @param siglas
     * @param prefijo
     * @param rangoInicial
     * @param rangoFinal
     * @param ultimoConsecutivo
     */
    public void crearFila(int codigo, String nombre, String siglas, String prefijo, String rangoInicial, String rangoFinal, String ultimoConsecutivo){
        model.addRow(new Object[]{codigo, nombre, siglas, prefijo, rangoInicial, rangoFinal, ultimoConsecutivo});
    }
    
    /**
     * Toma el ultimo cajero seleccionado dentro de la tabla y lo retorna
     * @return 
     */
    public CajeroVO obtenerCajeroSeleccionado(){
        CajeroVO cajeroSeleccionado = null;
        int index = tablaCajeros.getSelectedRow();
        if(index != -1){
            TableModel tableModel = tablaCajeros.getModel();
            cajeroSeleccionado = new CajeroVO();
            cajeroSeleccionado.setCodigo(Integer.parseInt(tableModel.getValueAt(index, 0).toString()));
            cajeroSeleccionado.setNombre(tableModel.getValueAt(index, 1).toString());
            cajeroSeleccionado.setSiglas(tableModel.getValueAt(index, 2).toString());
            cajeroSeleccionado.setPrefijo(tableModel.getValueAt(index, 3).toString());
            cajeroSeleccionado.setRangoInicial(tableModel.getValueAt(index, 4).toString());
            cajeroSeleccionado.setRangoFinal(tableModel.getValueAt(index, 5).toString());
            cajeroSeleccionado.setUltimoConsecutivo(tableModel.getValueAt(index, 6).toString());
        } else {
            JOptionPane.showMessageDialog(null, ningunCajeroSeleccionado);
        }
        return cajeroSeleccionado;
    }
    
    /**
     * Toma todos los cajeros que se encuentran dentro de la base de datos y 
     * las ingresa en la tabla
     */
    public void llenarTabla(){
        Formulario.eliminarTodasLasFilas(model);
        List<CajeroVO> cajeros = coordinador.buscarTodosLosCajeros();
        if(!cajeros.isEmpty()){
            for (CajeroVO cajero : cajeros) {
                crearFila(cajero.getCodigo(), cajero.getNombre(), cajero.getSiglas(), cajero.getPrefijo(), cajero.getRangoInicial(), cajero.getRangoFinal(), cajero.getUltimoConsecutivo());
            }
        } else {
            JOptionPane.showMessageDialog(null, noHayCajeros);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCajeros = new javax.swing.JTable();
        botonAgregar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonRefrescarTabla = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        etiquetaTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiquetaTitulo.setText("Cajeros");

        campoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyPressed(evt);
            }
        });

        tablaCajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Siglas", "Prefijo", "RangoInicial", "RangoFinal", "UltimoConsecutivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCajeros);

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/plus_32.png"))); // NOI18N
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/pencil_32.png"))); // NOI18N
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/delete_32.png"))); // NOI18N
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonRefrescarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarTablaActionPerformed(evt);
            }
        });

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/home_32.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(etiquetaTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRefrescarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonEditar, botonEliminar, botonRefrescarTabla, botonSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir)
                    .addComponent(botonEditar)
                    .addComponent(botonEliminar)
                    .addComponent(botonAgregar)
                    .addComponent(botonRefrescarTabla))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonAgregar, botonEditar, botonEliminar, botonRefrescarTabla, botonSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tablaCajeros.getModel());
            tablaCajeros.setRowSorter(rowSorter);
            String text = campoBusqueda.getText();
            if (text.trim().length() == 0) {
                rowSorter.setRowFilter(null);
            } else {
                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            }
        }
    }//GEN-LAST:event_campoBusquedaKeyPressed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        CrearCajero crearCajero = new CrearCajero();
        crearCajero.setVisible(true);
        crearCajero.setCoordinador(coordinador);
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        int fila = tablaCajeros.convertRowIndexToModel(tablaCajeros.getSelectedRow());
        if(fila != -1){
            TableModel modelo = tablaCajeros.getModel();
            EditarCajero editarCajero = new EditarCajero();
            editarCajero.setVisible(true);
            editarCajero.setCoordinador(coordinador);
            editarCajero.getCampoCodigo().setText(modelo.getValueAt(fila, 0).toString());
            editarCajero.getCampoNombre().setText(modelo.getValueAt(fila, 1).toString());
            editarCajero.getCampoSiglas().setText(modelo.getValueAt(fila, 2).toString());
            editarCajero.getCampoPrefijo().setText(modelo.getValueAt(fila, 3).toString());
            editarCajero.getCampoRangoInicial().setText(modelo.getValueAt(fila, 4).toString());
            editarCajero.getCampoRangoFinal().setText(modelo.getValueAt(fila, 5).toString());
            editarCajero.getCampoUltimoConsecutivo().setText(modelo.getValueAt(fila, 6).toString());
        } else {
            JOptionPane.showMessageDialog(null, ningunCajeroSeleccionado);
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        CajeroVO cajero = obtenerCajeroSeleccionado();
        if(cajero != null){
            int confirmacion = JOptionPane.showConfirmDialog(null, confirmacionEliminar);
            if(JOptionPane.YES_OPTION == confirmacion){
                boolean eliminada = coordinador.eliminarCajero(cajero.getCodigo());
                if(eliminada){
                    int fila = tablaCajeros.convertRowIndexToModel(tablaCajeros.getSelectedRow());
                    model = (DefaultTableModel)tablaCajeros.getModel();
                    model.removeRow(fila);
                    JOptionPane.showMessageDialog(null, cajeroEliminado);
                    llenarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, cajeroNoEliminado);
                }
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonRefrescarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarTablaActionPerformed
        llenarTabla();
    }//GEN-LAST:event_botonRefrescarTablaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_botonSalirActionPerformed

    public Coordinador getCoordinador() {
        return coordinador;
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRefrescarTabla;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCajeros;
    // End of variables declaration//GEN-END:variables
}
