/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.datosBasicos.cajeros;

import controlador.Coordinador;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.vo.datosBasicos.CajeroVO;
import utilidades.Formulario;

/**
 *
 * @author Victor Del Rio Prens
 */
public class CrearCajero extends javax.swing.JFrame {
    final String cajeroCreada = "El cajero fue creado con exito.";
    final String cajeroNoCreado = "Problemas al crear el cajero.";
    Coordinador coordinador;
    List<Object> campos;
    List<Object> botones;
    /**
     * Creates new form CrearCajero
     */
    public CrearCajero() {
        initComponents();
        setLocationRelativeTo(null);
        campos = Formulario.obtenerElementos(JTextField.class, getComponents());
        botones = Formulario.obtenerElementos(JButton.class, getComponents());
    }
    
    /**
     * Toma todos los campos que se encuentran dentro del formulario y los retorna
     * en un objeto
     * @return 
     */
    public CajeroVO obtenerCajero(){
        CajeroVO cajero = new CajeroVO(campoNombre.getText(),campoSiglas.getText(),campoPrefijo.getText(),campoRangoFinal.getText(),campoRangoFinal.getText(),campoUltimoConsecutivo.getText());
        return cajero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoUltimoConsecutivo = new javax.swing.JTextField();
        etiquetaUltimoConsecutivo = new javax.swing.JLabel();
        campoPrefijo = new javax.swing.JTextField();
        etiquetaPrefijo = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        campoRangoInicial = new javax.swing.JTextField();
        etiquetaRangoInicial = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etiquetaRangoFinal = new javax.swing.JLabel();
        campoRangoFinal = new javax.swing.JTextField();
        campoSiglas = new javax.swing.JTextField();
        etiquetaSiglas = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        etiquetaUltimoConsecutivo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaUltimoConsecutivo.setText("Ultimo Consecutivo:");

        etiquetaPrefijo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaPrefijo.setText("Prefijo:");

        etiquetaTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiquetaTitulo.setText("Crear Cajero");

        etiquetaRangoInicial.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaRangoInicial.setText("Rango Inicial:");

        etiquetaNombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaNombre.setText("Nombre:");

        etiquetaRangoFinal.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaRangoFinal.setText("Rango Final:");

        etiquetaSiglas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaSiglas.setText("Siglas:");

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/save_32.png"))); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/home_32.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaNombre)
                            .addComponent(etiquetaSiglas)
                            .addComponent(etiquetaPrefijo)
                            .addComponent(etiquetaRangoInicial)
                            .addComponent(etiquetaRangoFinal)
                            .addComponent(etiquetaUltimoConsecutivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campoUltimoConsecutivo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(campoRangoFinal)
                                .addComponent(campoSiglas)
                                .addComponent(campoPrefijo)
                                .addComponent(campoRangoInicial)
                                .addComponent(campoNombre)))))
                .addGap(47, 47, 47))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonGuardar, botonSalir});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {etiquetaNombre, etiquetaPrefijo, etiquetaRangoFinal, etiquetaRangoInicial, etiquetaSiglas, etiquetaUltimoConsecutivo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(etiquetaSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(etiquetaPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(etiquetaRangoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoPrefijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoRangoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(etiquetaRangoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRangoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(etiquetaUltimoConsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUltimoConsecutivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonGuardar)
                    .addComponent(botonSalir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if(Formulario.validarCamposVacios(campos)){
            boolean creada = coordinador.crearCajero(obtenerCajero());
            Formulario.limpiarCampos(campos);
            String mensaje = (creada) ? cajeroCreada : cajeroNoCreado;
            JOptionPane.showMessageDialog(null, mensaje);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_botonSalirActionPerformed

    public Coordinador getCoordinador() {
        return coordinador;
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPrefijo;
    private javax.swing.JTextField campoRangoFinal;
    private javax.swing.JTextField campoRangoInicial;
    private javax.swing.JTextField campoSiglas;
    private javax.swing.JTextField campoUltimoConsecutivo;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPrefijo;
    private javax.swing.JLabel etiquetaRangoFinal;
    private javax.swing.JLabel etiquetaRangoInicial;
    private javax.swing.JLabel etiquetaSiglas;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel etiquetaUltimoConsecutivo;
    // End of variables declaration//GEN-END:variables
}
