/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.datosBasicos.fuentesDeIngresos;

import controlador.Coordinador;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.vo.datosBasicos.FuenteDeIngresosVO;
import utilidades.Formulario;
import vista.datosBasicos.ForcedListSelectionModel;

/**
 *
 * @author Victor Del Rio Prens
 */
public class FuentesDeIngresos extends javax.swing.JFrame {
    private final String noHayFuentesDeIngresos = "Actualmente no existen fuentes de ingresos dentro de la base de datos.";
    private final String ningunaFuenteDeIngresosSeleccionada = "Por favor seleccione una fuente de ingresos.";
    private final String fuenteDeIngresosEliminada = "La fuente de ingresos fue eliminada con exito.";
    private final String fuenteDeIngresosNoEliminada = "Existe un problema al tratar de eliminar la fuente de ingresos.";
    private final String confirmacionEliminar = "¿Desea eliminar esta fuente de ingresos?";
    Coordinador coordinador;
    DefaultTableModel model;
    /**
     * Creates new form FuentesDeIngreso
     */
    public FuentesDeIngresos() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tablaFuentesDeIngresos.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tablaFuentesDeIngresos.setDefaultRenderer(String.class, centerRenderer);
        tablaFuentesDeIngresos.setDefaultRenderer(Integer.class, centerRenderer);
        tablaFuentesDeIngresos.setSelectionModel(new ForcedListSelectionModel());
    }
    
    /**
     * Permite crear una fila dentro de la tabla
     * @param codigo
     * @param nombre
     */
    public void crearFila(int codigo, String nombre){
        model.addRow(new Object[]{codigo, nombre});
    }
    
    /**
     * Toma la ultima fuente de ingresos seleccionada dentro de la tabla y la retorna
     * @return 
     */
    public FuenteDeIngresosVO obtenerFuenteDeIngresosSeleccionada(){
        FuenteDeIngresosVO lineaDeArticulosSeleccionada = null;
        int index = tablaFuentesDeIngresos.getSelectedRow();
        if(index != -1){
            TableModel tableModel = tablaFuentesDeIngresos.getModel();
            lineaDeArticulosSeleccionada = new FuenteDeIngresosVO();
            lineaDeArticulosSeleccionada.setCodigo(Integer.parseInt(tableModel.getValueAt(index, 0).toString()));
            lineaDeArticulosSeleccionada.setNombre(tableModel.getValueAt(index, 1).toString());
            
        } else {
            JOptionPane.showMessageDialog(null, ningunaFuenteDeIngresosSeleccionada);
        }
        return lineaDeArticulosSeleccionada;
    }
    
    /**
     * Toma todas las fuentes de ingresos que se encuentran dentro de la base de datos y 
     * las ingresa en la tabla
     */
    public void llenarTabla(){
        Formulario.eliminarTodasLasFilas(model);
        List<FuenteDeIngresosVO> fuentesDeIngresos = coordinador.buscarTodasLasFuentesDeIngresos();
        if(!fuentesDeIngresos.isEmpty()){
            for (FuenteDeIngresosVO fuenteDeIngresos : fuentesDeIngresos) {
                crearFila(fuenteDeIngresos.getCodigo(), fuenteDeIngresos.getNombre());
            }
        } else {
            JOptionPane.showMessageDialog(null, noHayFuentesDeIngresos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonSalir = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        etiquetaTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFuentesDeIngresos = new javax.swing.JTable();
        campoBusqueda = new javax.swing.JTextField();
        botonRefrescarTabla = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/home_32.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/pencil_32.png"))); // NOI18N
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/plus_32.png"))); // NOI18N
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        etiquetaTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiquetaTitulo.setText("Fuentes De Ingresos");

        tablaFuentesDeIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaFuentesDeIngresos);

        campoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyPressed(evt);
            }
        });

        botonRefrescarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarTablaActionPerformed(evt);
            }
        });

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/delete_32.png"))); // NOI18N
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRefrescarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAgregar, botonEditar, botonEliminar, botonRefrescarTabla, botonSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTitulo)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir)
                    .addComponent(botonEditar)
                    .addComponent(botonEliminar)
                    .addComponent(botonAgregar)
                    .addComponent(botonRefrescarTabla))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonAgregar, botonEditar, botonEliminar, botonRefrescarTabla, botonSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        int fila = tablaFuentesDeIngresos.convertRowIndexToModel(tablaFuentesDeIngresos.getSelectedRow());
        if(fila != -1){
            TableModel modelo = tablaFuentesDeIngresos.getModel();
            EditarFuenteDeIngresos editarFuenteDeIngresos = new EditarFuenteDeIngresos();
            editarFuenteDeIngresos.setVisible(true);
            editarFuenteDeIngresos.setCoordinador(coordinador);
            editarFuenteDeIngresos.getCampoCodigo().setText(modelo.getValueAt(fila, 0).toString());
            editarFuenteDeIngresos.getCampoNombre().setText(modelo.getValueAt(fila, 1).toString());
        } else {
            JOptionPane.showMessageDialog(null, ningunaFuenteDeIngresosSeleccionada);
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        CrearFuenteDeIngresos crearFuenteDeIngresos = new CrearFuenteDeIngresos();
        crearFuenteDeIngresos.setVisible(true);
        crearFuenteDeIngresos.setCoordinador(coordinador);
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void campoBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(tablaFuentesDeIngresos.getModel());
            tablaFuentesDeIngresos.setRowSorter(rowSorter);
            String text = campoBusqueda.getText();
            if (text.trim().length() == 0) {
                rowSorter.setRowFilter(null);
            } else {
                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            }
        }
    }//GEN-LAST:event_campoBusquedaKeyPressed

    private void botonRefrescarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarTablaActionPerformed
        llenarTabla();
    }//GEN-LAST:event_botonRefrescarTablaActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        FuenteDeIngresosVO fuenteDeIngresos = obtenerFuenteDeIngresosSeleccionada();
        if(fuenteDeIngresos != null){
            int confirmacion = JOptionPane.showConfirmDialog(null, confirmacionEliminar);
            if(JOptionPane.YES_OPTION == confirmacion){
                boolean eliminada = coordinador.eliminarFuenteDeIngresos(fuenteDeIngresos.getCodigo());
                if(eliminada){
                    int fila = tablaFuentesDeIngresos.convertRowIndexToModel(tablaFuentesDeIngresos.getSelectedRow());
                    model = (DefaultTableModel)tablaFuentesDeIngresos.getModel();
                    model.removeRow(fila);
                    JOptionPane.showMessageDialog(null, fuenteDeIngresosEliminada);
                    llenarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, fuenteDeIngresosNoEliminada);
                }
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    public Coordinador getCoordinador() {
        return coordinador;
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRefrescarTabla;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFuentesDeIngresos;
    // End of variables declaration//GEN-END:variables
}
