/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Coordinador;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.UIManager;
import vista.datosBasicos.ActualizarDatosGenerales;
import vista.datosBasicos.bodegas.Bodegas;
import vista.datosBasicos.cajeros.Cajeros;
import vista.datosBasicos.empresas.Empresas;
import vista.datosBasicos.fuentesDeIngresos.FuentesDeIngresos;
import vista.datosBasicos.lineasDeArticulos.LineasDeArticulos;
import vista.datosBasicos.parametrosIva.ParametrosIVA;
import vista.datosBasicos.proveedores.Proveedores;
import vista.datosBasicos.puntosDeVenta.PuntosDeVenta;
import vista.datosBasicos.ResolucionDIAN;
import vista.datosBasicos.teceros.Terceros;
import vista.datosBasicos.unidadesDeMedida.UnidadesDeMedida;
import vista.datosBasicos.vendedores.Vendedores;
import vista.datosBasicos.controlConsecutivos.ConsecutivosArticulos;
import vista.datosBasicos.controlConsecutivos.ConsecutivosBodegas;
import vista.datosBasicos.controlConsecutivos.ConsecutivosEmpresas;
import vista.datosBasicos.controlConsecutivos.ConsecutivosIngresos;
import vista.datosBasicos.controlConsecutivos.ConsecutivosLineas;
import vista.datosBasicos.controlConsecutivos.ConsecutivosProveedores;
import vista.datosBasicos.controlConsecutivos.ConsecutivosPuntosDeVenta;
import vista.datosBasicos.controlConsecutivos.ConsecutivosSalidas;

/**
 *
 * @author Victor Del Rio Prens
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    Coordinador coordinador;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
//        try{
//            JFrame.setDefaultLookAndFeelDecorated(true);
//            JDialog.setDefaultLookAndFeelDecorated(true);
//            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
//            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
//        }
//        catch (Exception e){
//            e.printStackTrace();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeNavegacion = new javax.swing.JMenuBar();
        menuDatosBasicos = new javax.swing.JMenu();
        subMenuConsecutivos = new javax.swing.JMenu();
        menuItemConsecutivosLineas = new javax.swing.JMenuItem();
        menuItemConsecutivosArticulos = new javax.swing.JMenuItem();
        menuItemConsecutivosProveedores = new javax.swing.JMenuItem();
        menuItemConsecutivosBodegas = new javax.swing.JMenuItem();
        menuItemConsecutivosEmpresas = new javax.swing.JMenuItem();
        menuItemConsecutivosPuntosDeVenta = new javax.swing.JMenuItem();
        menuItemConsecutivosIngresos = new javax.swing.JMenuItem();
        menuItemConsecutivosSalidas = new javax.swing.JMenuItem();
        menuItemBodegas = new javax.swing.JMenuItem();
        menuItemLineasDeArticulos = new javax.swing.JMenuItem();
        menuItemArticulos = new javax.swing.JMenuItem();
        menuItemProveedores = new javax.swing.JMenuItem();
        menuItemTerceros = new javax.swing.JMenuItem();
        menuItemEmpresas = new javax.swing.JMenuItem();
        menuItemPuntosDeVenta = new javax.swing.JMenuItem();
        menuItemFuentesDeIngresos = new javax.swing.JMenuItem();
        menuItemUnidadesDeMedida = new javax.swing.JMenuItem();
        menuItemVendedores = new javax.swing.JMenuItem();
        menuItemCajeros = new javax.swing.JMenuItem();
        menuItemResolucionDian = new javax.swing.JMenuItem();
        menuItemParametrosIVA = new javax.swing.JMenuItem();
        menuItemActualizacionDatosGenerales = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuMovimientos = new javax.swing.JMenu();
        menuInformes = new javax.swing.JMenu();
        menuUtilidades = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuDatosBasicos.setText("Datos Básicos");

        subMenuConsecutivos.setText("Control de Consecutivos");

        menuItemConsecutivosLineas.setText("líneas");
        menuItemConsecutivosLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsecutivosLineasActionPerformed(evt);
            }
        });
        subMenuConsecutivos.add(menuItemConsecutivosLineas);

        menuItemConsecutivosArticulos.setText("Artículos");
        menuItemConsecutivosArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsecutivosArticulosActionPerformed(evt);
            }
        });
        subMenuConsecutivos.add(menuItemConsecutivosArticulos);

        menuItemConsecutivosProveedores.setText("Proveedores");
        menuItemConsecutivosProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsecutivosProveedoresActionPerformed(evt);
            }
        });
        subMenuConsecutivos.add(menuItemConsecutivosProveedores);

        menuItemConsecutivosBodegas.setText("Bodegas");
        menuItemConsecutivosBodegas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsecutivosBodegasActionPerformed(evt);
            }
        });
        subMenuConsecutivos.add(menuItemConsecutivosBodegas);

        menuItemConsecutivosEmpresas.setText("Empresas");
        menuItemConsecutivosEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsecutivosEmpresasActionPerformed(evt);
            }
        });
        subMenuConsecutivos.add(menuItemConsecutivosEmpresas);

        menuItemConsecutivosPuntosDeVenta.setText("Puntos de Venta");
        menuItemConsecutivosPuntosDeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsecutivosPuntosDeVentaActionPerformed(evt);
            }
        });
        subMenuConsecutivos.add(menuItemConsecutivosPuntosDeVenta);

        menuItemConsecutivosIngresos.setText("Ingresos");
        menuItemConsecutivosIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsecutivosIngresosActionPerformed(evt);
            }
        });
        subMenuConsecutivos.add(menuItemConsecutivosIngresos);

        menuItemConsecutivosSalidas.setText("Salidas");
        menuItemConsecutivosSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsecutivosSalidasActionPerformed(evt);
            }
        });
        subMenuConsecutivos.add(menuItemConsecutivosSalidas);

        menuDatosBasicos.add(subMenuConsecutivos);

        menuItemBodegas.setText("Bodegas");
        menuItemBodegas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBodegasActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemBodegas);

        menuItemLineasDeArticulos.setText("Líneas de Articulos");
        menuItemLineasDeArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLineasDeArticulosActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemLineasDeArticulos);

        menuItemArticulos.setText("Articulos");
        menuItemArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemArticulosActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemArticulos);

        menuItemProveedores.setText("Proveedores");
        menuItemProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProveedoresActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemProveedores);

        menuItemTerceros.setText("Terceros");
        menuItemTerceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTercerosActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemTerceros);

        menuItemEmpresas.setText("Empresas");
        menuItemEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmpresasActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemEmpresas);

        menuItemPuntosDeVenta.setText("Puntos de Venta");
        menuItemPuntosDeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPuntosDeVentaActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemPuntosDeVenta);

        menuItemFuentesDeIngresos.setText("Fuentes de Ingresos");
        menuItemFuentesDeIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuentesDeIngresosActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemFuentesDeIngresos);

        menuItemUnidadesDeMedida.setText("Unidades de Medida");
        menuItemUnidadesDeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUnidadesDeMedidaActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemUnidadesDeMedida);

        menuItemVendedores.setText("Vendedores");
        menuItemVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVendedoresActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemVendedores);

        menuItemCajeros.setText("Cajeros");
        menuItemCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCajerosActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemCajeros);

        menuItemResolucionDian.setText("Resolucion de la Dian");
        menuItemResolucionDian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemResolucionDianActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemResolucionDian);

        menuItemParametrosIVA.setText("Parametros del IVA");
        menuItemParametrosIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemParametrosIVAActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemParametrosIVA);

        menuItemActualizacionDatosGenerales.setText("Actualizacion de Datos Generales");
        menuItemActualizacionDatosGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizacionDatosGeneralesActionPerformed(evt);
            }
        });
        menuDatosBasicos.add(menuItemActualizacionDatosGenerales);

        menuItemSalir.setText("Salir");
        menuDatosBasicos.add(menuItemSalir);

        barraDeNavegacion.add(menuDatosBasicos);

        menuMovimientos.setText("Movimientos");
        barraDeNavegacion.add(menuMovimientos);

        menuInformes.setText("Informes");
        barraDeNavegacion.add(menuInformes);

        menuUtilidades.setText("Utilidades del Sistema");
        barraDeNavegacion.add(menuUtilidades);

        setJMenuBar(barraDeNavegacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLineasDeArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLineasDeArticulosActionPerformed
        LineasDeArticulos lineasDeArticulos = new LineasDeArticulos();
        lineasDeArticulos.setVisible(true);
        lineasDeArticulos.setCoordinador(coordinador);
        lineasDeArticulos.llenarTabla();
    }//GEN-LAST:event_menuItemLineasDeArticulosActionPerformed

    private void menuItemUnidadesDeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUnidadesDeMedidaActionPerformed
        UnidadesDeMedida UnidadesDeMedida = new UnidadesDeMedida();
        UnidadesDeMedida.setVisible(true);
        UnidadesDeMedida.setCoordinador(coordinador);
        UnidadesDeMedida.llenarTabla();
    }//GEN-LAST:event_menuItemUnidadesDeMedidaActionPerformed

    private void menuItemPuntosDeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPuntosDeVentaActionPerformed
        PuntosDeVenta puntosDeVenta = new PuntosDeVenta();
        puntosDeVenta.setVisible(true);
        puntosDeVenta.setCoordinador(coordinador);
        puntosDeVenta.llenarTabla();
    }//GEN-LAST:event_menuItemPuntosDeVentaActionPerformed

    private void menuItemBodegasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBodegasActionPerformed
        Bodegas bodegas = new Bodegas();
        bodegas.setVisible(true);
        bodegas.setCoordinador(coordinador);
        bodegas.llenarTabla();
    }//GEN-LAST:event_menuItemBodegasActionPerformed

    private void menuItemProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProveedoresActionPerformed
        Proveedores proveedores = new Proveedores();
        proveedores.setVisible(true);
        proveedores.setCoordinador(coordinador);
        proveedores.llenarTabla();
    }//GEN-LAST:event_menuItemProveedoresActionPerformed

    private void menuItemTercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTercerosActionPerformed
        Terceros terceros = new Terceros();
        terceros.setVisible(true);
        terceros.setCoordinador(coordinador);
        terceros.llenarTabla();
    }//GEN-LAST:event_menuItemTercerosActionPerformed

    private void menuItemEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmpresasActionPerformed
        Empresas empresas = new Empresas();
        empresas.setVisible(true);
        empresas.setCoordinador(coordinador);
        empresas.llenarTabla();
    }//GEN-LAST:event_menuItemEmpresasActionPerformed

    private void menuItemFuentesDeIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuentesDeIngresosActionPerformed
        FuentesDeIngresos fuentesDeIngresos = new FuentesDeIngresos();
        fuentesDeIngresos.setVisible(true);
        fuentesDeIngresos.setCoordinador(coordinador);
        fuentesDeIngresos.llenarTabla();
    }//GEN-LAST:event_menuItemFuentesDeIngresosActionPerformed

    private void menuItemVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVendedoresActionPerformed
        Vendedores vendedores = new Vendedores();
        vendedores.setVisible(true);
        vendedores.setCoordinador(coordinador);
        vendedores.llenarTabla();
    }//GEN-LAST:event_menuItemVendedoresActionPerformed

    private void menuItemCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCajerosActionPerformed
        Cajeros cajeros = new Cajeros();
        cajeros.setVisible(true);
        cajeros.setCoordinador(coordinador);
        cajeros.llenarTabla();
    }//GEN-LAST:event_menuItemCajerosActionPerformed

    private void menuItemResolucionDianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemResolucionDianActionPerformed
        ResolucionDIAN vistaResolucionDIAN = new ResolucionDIAN();
        vistaResolucionDIAN.setVisible(true);
    }//GEN-LAST:event_menuItemResolucionDianActionPerformed

    private void menuItemParametrosIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemParametrosIVAActionPerformed
        ParametrosIVA parametrosIVA = new ParametrosIVA();
        parametrosIVA.setVisible(true);
        parametrosIVA.setCoordinador(coordinador);
        parametrosIVA.llenarTabla();
    }//GEN-LAST:event_menuItemParametrosIVAActionPerformed

    private void menuItemActualizacionDatosGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizacionDatosGeneralesActionPerformed
        ActualizarDatosGenerales vistaActualizarDatosGenerales = new ActualizarDatosGenerales();
        vistaActualizarDatosGenerales.setVisible(true);
    }//GEN-LAST:event_menuItemActualizacionDatosGeneralesActionPerformed

    private void menuItemConsecutivosLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsecutivosLineasActionPerformed
        ConsecutivosLineas vistaConsecutivosLineas = new ConsecutivosLineas();
        vistaConsecutivosLineas.setVisible(true);
    }//GEN-LAST:event_menuItemConsecutivosLineasActionPerformed

    private void menuItemConsecutivosArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsecutivosArticulosActionPerformed
        ConsecutivosArticulos vistaConsecutivosArticulos = new ConsecutivosArticulos();
        vistaConsecutivosArticulos.setVisible(true);
    }//GEN-LAST:event_menuItemConsecutivosArticulosActionPerformed

    private void menuItemConsecutivosProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsecutivosProveedoresActionPerformed
        ConsecutivosProveedores vistaConsecutivosProveedores = new ConsecutivosProveedores();
        vistaConsecutivosProveedores.setVisible(true);
    }//GEN-LAST:event_menuItemConsecutivosProveedoresActionPerformed

    private void menuItemConsecutivosBodegasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsecutivosBodegasActionPerformed
        ConsecutivosBodegas vistaConsecutivosBodegas = new ConsecutivosBodegas();
        vistaConsecutivosBodegas.setVisible(true);
    }//GEN-LAST:event_menuItemConsecutivosBodegasActionPerformed

    private void menuItemConsecutivosEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsecutivosEmpresasActionPerformed
        ConsecutivosEmpresas vistaConsecutivosEmpresas = new ConsecutivosEmpresas();
        vistaConsecutivosEmpresas.setVisible(true);
    }//GEN-LAST:event_menuItemConsecutivosEmpresasActionPerformed

    private void menuItemConsecutivosPuntosDeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsecutivosPuntosDeVentaActionPerformed
        ConsecutivosPuntosDeVenta vistaConsecutivosPuntosDeVenta = new ConsecutivosPuntosDeVenta();
        vistaConsecutivosPuntosDeVenta.setVisible(true);
    }//GEN-LAST:event_menuItemConsecutivosPuntosDeVentaActionPerformed

    private void menuItemConsecutivosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsecutivosIngresosActionPerformed
        ConsecutivosIngresos vistaConsecutivosIngresos = new ConsecutivosIngresos();
        vistaConsecutivosIngresos.setVisible(true);
    }//GEN-LAST:event_menuItemConsecutivosIngresosActionPerformed

    private void menuItemConsecutivosSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsecutivosSalidasActionPerformed
        ConsecutivosSalidas vistaConsecutivosSalidas = new ConsecutivosSalidas();
        vistaConsecutivosSalidas.setVisible(true);
    }//GEN-LAST:event_menuItemConsecutivosSalidasActionPerformed

    private void menuItemArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemArticulosActionPerformed
       
    }//GEN-LAST:event_menuItemArticulosActionPerformed

    public Coordinador getCoordinador() {
        return coordinador;
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeNavegacion;
    private javax.swing.JMenu menuDatosBasicos;
    private javax.swing.JMenu menuInformes;
    private javax.swing.JMenuItem menuItemActualizacionDatosGenerales;
    private javax.swing.JMenuItem menuItemArticulos;
    private javax.swing.JMenuItem menuItemBodegas;
    private javax.swing.JMenuItem menuItemCajeros;
    private javax.swing.JMenuItem menuItemConsecutivosArticulos;
    private javax.swing.JMenuItem menuItemConsecutivosBodegas;
    private javax.swing.JMenuItem menuItemConsecutivosEmpresas;
    private javax.swing.JMenuItem menuItemConsecutivosIngresos;
    private javax.swing.JMenuItem menuItemConsecutivosLineas;
    private javax.swing.JMenuItem menuItemConsecutivosProveedores;
    private javax.swing.JMenuItem menuItemConsecutivosPuntosDeVenta;
    private javax.swing.JMenuItem menuItemConsecutivosSalidas;
    private javax.swing.JMenuItem menuItemEmpresas;
    private javax.swing.JMenuItem menuItemFuentesDeIngresos;
    private javax.swing.JMenuItem menuItemLineasDeArticulos;
    private javax.swing.JMenuItem menuItemParametrosIVA;
    private javax.swing.JMenuItem menuItemProveedores;
    private javax.swing.JMenuItem menuItemPuntosDeVenta;
    private javax.swing.JMenuItem menuItemResolucionDian;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemTerceros;
    private javax.swing.JMenuItem menuItemUnidadesDeMedida;
    private javax.swing.JMenuItem menuItemVendedores;
    private javax.swing.JMenu menuMovimientos;
    private javax.swing.JMenu menuUtilidades;
    private javax.swing.JMenu subMenuConsecutivos;
    // End of variables declaration//GEN-END:variables
}
