/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.datosBasicos.proveedores;

import controlador.Coordinador;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.vo.datosBasicos.ProveedorVO;
import utilidades.Constantes;
import utilidades.Formulario;

/**
 *
 * @author Victor Del Rio Prens
 */
public class EditarProveedor extends javax.swing.JFrame {
    final String proveedorEditado = "El proveedor fue editado con exito.";
    final String proveedorNoEditado = "Problemas al editar el proveedor.";
    Coordinador coordinador;
    List<Object> campos;
    List<Object> botones;
    
    /**
     * Creates new form EditarCajero
     */
    public EditarProveedor() {
        initComponents();
        setLocationRelativeTo(null);
        campos = Formulario.obtenerElementos(JTextField.class, getComponents());
        botones = Formulario.obtenerElementos(JButton.class, getComponents());
    }
    
    /**
     * Toma todos los campos que se encuentran dentro del formulario y los retorna
     * @return 
     */
    public ProveedorVO obtenerProveedor(){
        ProveedorVO proveedor = new ProveedorVO();
        try {
            proveedor.setCodigo(Integer.parseInt(campoCodigo.getText()));
            proveedor.setNombre(campoNombre.getText());
            proveedor.setNit(campoNit.getText());
            proveedor.setDireccion(campoDireccion.getText());
            proveedor.setTelefonos(campoTelefonos.getText());
            proveedor.setRepresentante(campoRepresentante.getText());
            proveedor.setEmail(campoEmail.getText());
            proveedor.setFax(campoFax.getText());
            proveedor.setCuentaContable(campoCuentaContable.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, Constantes.codigoValido);
        }
        return proveedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaNombre = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etiquetaRepresentante = new javax.swing.JLabel();
        campoTelefonos = new javax.swing.JTextField();
        etiquetaTelefonos = new javax.swing.JLabel();
        campoRepresentante = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        campoNit = new javax.swing.JTextField();
        etiquetaCodigo = new javax.swing.JLabel();
        etiquetaNit = new javax.swing.JLabel();
        etiquetaEmail = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        campoDireccion = new javax.swing.JTextField();
        etiquetaDireccion = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        campoFax = new javax.swing.JTextField();
        campoCuentaContable = new javax.swing.JTextField();
        etiquetaCuentaContable = new javax.swing.JLabel();
        etiquetaFax = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        etiquetaNombre.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaNombre.setText("Nombre:");

        etiquetaTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiquetaTitulo.setText("Editar Proveedor");

        etiquetaRepresentante.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaRepresentante.setText("Representante:");

        etiquetaTelefonos.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaTelefonos.setText("Telefonos:");

        etiquetaCodigo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaCodigo.setText("Código Proveedor:");

        etiquetaNit.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaNit.setText("Nit:");

        etiquetaEmail.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaEmail.setText("Email:");

        campoCodigo.setEditable(false);

        etiquetaDireccion.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaDireccion.setText("Direccion:");

        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/save_32.png"))); // NOI18N
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/home_32.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        etiquetaCuentaContable.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaCuentaContable.setText("Cuenta Contable:");

        etiquetaFax.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        etiquetaFax.setText("Fax:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etiquetaFax)
                                .addComponent(etiquetaCuentaContable))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campoFax, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoCuentaContable))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etiquetaCodigo)
                                .addComponent(etiquetaNombre)
                                .addComponent(etiquetaNit)
                                .addComponent(etiquetaDireccion)
                                .addComponent(etiquetaTelefonos)
                                .addComponent(etiquetaRepresentante)
                                .addComponent(etiquetaEmail))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(campoNit)
                                    .addComponent(campoDireccion)
                                    .addComponent(campoTelefonos)
                                    .addComponent(campoNombre)
                                    .addComponent(campoRepresentante, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {etiquetaCodigo, etiquetaCuentaContable, etiquetaDireccion, etiquetaEmail, etiquetaFax, etiquetaNit, etiquetaNombre, etiquetaRepresentante, etiquetaTelefonos});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonGuardar, botonSalir});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoCodigo, campoCuentaContable, campoDireccion, campoEmail, campoFax, campoNit, campoNombre, campoRepresentante, campoTelefonos});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaCodigo)
                        .addGap(22, 22, 22)
                        .addComponent(etiquetaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(etiquetaNit, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(etiquetaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(etiquetaTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoTelefonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(etiquetaRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(etiquetaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFax, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCuentaContable, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCuentaContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonGuardar)
                    .addComponent(botonSalir))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoCodigo, campoCuentaContable, campoDireccion, campoEmail, campoNit, campoNombre, campoRepresentante, campoTelefonos});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if(Formulario.validarCamposVacios(campos)){
            boolean creada = coordinador.editarProveedor(obtenerProveedor());
            Formulario.limpiarCampos(campos);
            String mensaje = (creada) ? proveedorEditado : proveedorNoEditado;
            JOptionPane.showMessageDialog(null, mensaje);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_botonSalirActionPerformed

    public JTextField getCampoCodigo() {
        return campoCodigo;
    }

    public void setCampoCodigo(JTextField campoCodigo) {
        this.campoCodigo = campoCodigo;
    }

    public JTextField getCampoNombre() {
        return campoNombre;
    }

    public JTextField getCampoDireccion() {
        return campoDireccion;
    }

    public void setCampoDireccion(JTextField campoDireccion) {
        this.campoDireccion = campoDireccion;
    }

    public JTextField getCampoEmail() {
        return campoEmail;
    }

    public void setCampoEmail(JTextField campoEmail) {
        this.campoEmail = campoEmail;
    }

    public JTextField getCampoFax() {
        return campoFax;
    }

    public void setCampoFax(JTextField campoFax) {
        this.campoFax = campoFax;
    }

    public JTextField getCampoNit() {
        return campoNit;
    }

    public void setCampoNit(JTextField campoNit) {
        this.campoNit = campoNit;
    }

    public JTextField getCampoRepresentante() {
        return campoRepresentante;
    }

    public void setCampoRepresentante(JTextField campoRepresentante) {
        this.campoRepresentante = campoRepresentante;
    }

    public JTextField getCampoTelefonos() {
        return campoTelefonos;
    }

    public void setCampoTelefonos(JTextField campoTelefonos) {
        this.campoTelefonos = campoTelefonos;
    }

    public JTextField getCampoCuentaContable() {
        return campoCuentaContable;
    }

    public void setCampoCuentaContable(JTextField campoCuentaContable) {
        this.campoCuentaContable = campoCuentaContable;
    }
    
    public void setCampoNombre(JTextField campoNombre) {
        this.campoNombre = campoNombre;
    }

    public Coordinador getCoordinador() {
        return coordinador;
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoCuentaContable;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoFax;
    private javax.swing.JTextField campoNit;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoRepresentante;
    private javax.swing.JTextField campoTelefonos;
    private javax.swing.JLabel etiquetaCodigo;
    private javax.swing.JLabel etiquetaCuentaContable;
    private javax.swing.JLabel etiquetaDireccion;
    private javax.swing.JLabel etiquetaEmail;
    private javax.swing.JLabel etiquetaFax;
    private javax.swing.JLabel etiquetaNit;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaRepresentante;
    private javax.swing.JLabel etiquetaTelefonos;
    private javax.swing.JLabel etiquetaTitulo;
    // End of variables declaration//GEN-END:variables
}
