/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.datosBasicos.proveedores;

import controlador.Coordinador;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.vo.datosBasicos.ProveedorVO;
import utilidades.Formulario;
import vista.datosBasicos.ForcedListSelectionModel;

/**
 *
 * @author Victor Del Rio Prens
 */
public class Proveedores extends javax.swing.JFrame {
    private final String noHayProveedores = "Actualmente no existen proveedores dentro de la base de datos.";
    private final String ningunProveedorSeleccionado = "Por favor seleccione un proveedor.";
    private final String proveedorEliminado = "El proveedor fue eliminado con exito.";
    private final String proveedorNoEliminado = "Existe un problema al tratar de eliminar el proveedor.";
    private final String confirmacionEliminar = "¿Desea eliminar este proveedor?";
    Coordinador coordinador;
    DefaultTableModel model;
    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tablaProveedores.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tablaProveedores.setDefaultRenderer(String.class, centerRenderer);
        tablaProveedores.setDefaultRenderer(Integer.class, centerRenderer);
        tablaProveedores.setSelectionModel(new ForcedListSelectionModel());
    }
    
    /**
     * Permite crear una fila dentro de la tabla
     * @param codigo
     * @param nombre
     * @param nit
     * @param direccion
     * @param telefonos
     * @param representante
     * @param email
     * @param fax
     * @param cuentaContable
     */
    public void crearFila(int codigo, String nombre, String nit, String direccion, String telefonos, String representante, String email, String fax, String cuentaContable){
        model.addRow(new Object[]{codigo, nombre, nit, direccion, telefonos, representante, email, fax, cuentaContable});
    }
    
    /**
     * Toma el ultimo proveedor seleccionado dentro de la tabla y lo retorna
     * @return 
     */
    public ProveedorVO obtenerProveedorSeleccionado(){
        ProveedorVO proveedorSeleccionado = null;
        int index = tablaProveedores.getSelectedRow();
        if(index != -1){
            TableModel tableModel = tablaProveedores.getModel();
            proveedorSeleccionado = new ProveedorVO();
            proveedorSeleccionado.setCodigo(Integer.parseInt(tableModel.getValueAt(index, 0).toString()));
            proveedorSeleccionado.setNombre(tableModel.getValueAt(index, 1).toString());
            proveedorSeleccionado.setNit(tableModel.getValueAt(index, 2).toString());
            proveedorSeleccionado.setDireccion(tableModel.getValueAt(index, 3).toString());
            proveedorSeleccionado.setTelefonos(tableModel.getValueAt(index, 4).toString());
            proveedorSeleccionado.setRepresentante(tableModel.getValueAt(index, 5).toString());
            proveedorSeleccionado.setEmail(tableModel.getValueAt(index, 6).toString());
            proveedorSeleccionado.setFax(tableModel.getValueAt(index, 7).toString());
            proveedorSeleccionado.setCuentaContable(tableModel.getValueAt(index, 8).toString());
        } else {
            JOptionPane.showMessageDialog(null, ningunProveedorSeleccionado);
        }
        return proveedorSeleccionado;
    }
    
    /**
     * Toma todos los proveedores que se encuentran dentro de la base de datos y 
     * las ingresa en la tabla
     */
    public void llenarTabla(){
        Formulario.eliminarTodasLasFilas(model);
        List<ProveedorVO> proveedores = coordinador.buscarTodosLosProveedores();
        if(!proveedores.isEmpty()){
            for (ProveedorVO proveedor : proveedores) {
                crearFila(proveedor.getCodigo(), proveedor.getNombre(), proveedor.getNit(), proveedor.getDireccion(), proveedor.getTelefonos(), proveedor.getRepresentante(), proveedor.getEmail(), proveedor.getFax(), proveedor.getCuentaContable());
            }
        } else {
            JOptionPane.showMessageDialog(null, noHayProveedores);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        campoBusqueda = new javax.swing.JTextField();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonRefrescarTabla = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        etiquetaTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        etiquetaTitulo.setText("Proveedores");

        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Nit", "Direccion", "Telefonos", "Representante", "Email", "Fax", "Cuenta Contable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProveedores);

        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/pencil_32.png"))); // NOI18N
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/delete_32.png"))); // NOI18N
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonRefrescarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarTablaActionPerformed(evt);
            }
        });

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/home_32.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/datosBasicos/plus_32.png"))); // NOI18N
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonRefrescarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botonAgregar, botonEditar, botonEliminar, botonRefrescarTabla, botonSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTitulo)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir)
                    .addComponent(botonEditar)
                    .addComponent(botonEliminar)
                    .addComponent(botonAgregar)
                    .addComponent(botonRefrescarTabla))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {botonAgregar, botonEditar, botonEliminar, botonRefrescarTabla, botonSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        int fila = tablaProveedores.convertRowIndexToModel(tablaProveedores.getSelectedRow());
        if(fila != -1){
            TableModel modelo = tablaProveedores.getModel();
            EditarProveedor editarProveedor = new EditarProveedor();
            editarProveedor.setVisible(true);
            editarProveedor.setCoordinador(coordinador);
            editarProveedor.getCampoCodigo().setText(modelo.getValueAt(fila, 0).toString());
            editarProveedor.getCampoNombre().setText(modelo.getValueAt(fila, 1).toString());
            editarProveedor.getCampoNit().setText(modelo.getValueAt(fila, 2).toString());
            editarProveedor.getCampoDireccion().setText(modelo.getValueAt(fila, 3).toString());
            editarProveedor.getCampoTelefonos().setText(modelo.getValueAt(fila, 4).toString());
            editarProveedor.getCampoRepresentante().setText(modelo.getValueAt(fila, 5).toString());
            editarProveedor.getCampoEmail().setText(modelo.getValueAt(fila, 6).toString());
            editarProveedor.getCampoFax().setText(modelo.getValueAt(fila, 7).toString());
            editarProveedor.getCampoCuentaContable().setText(modelo.getValueAt(fila, 8).toString());
        } else {
            JOptionPane.showMessageDialog(null, ningunProveedorSeleccionado);
        }
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        ProveedorVO proveedor = obtenerProveedorSeleccionado();
        if(proveedor != null){
            int confirmacion = JOptionPane.showConfirmDialog(null, confirmacionEliminar);
            if(JOptionPane.YES_OPTION == confirmacion){
                boolean eliminada = coordinador.eliminarProveedor(proveedor.getCodigo());
                if(eliminada){
                    int fila = tablaProveedores.convertRowIndexToModel(tablaProveedores.getSelectedRow());
                    model = (DefaultTableModel)tablaProveedores.getModel();
                    model.removeRow(fila);
                    JOptionPane.showMessageDialog(null, proveedorEliminado);
                    llenarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, proveedorNoEliminado);
                }
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonRefrescarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarTablaActionPerformed
        llenarTabla();
    }//GEN-LAST:event_botonRefrescarTablaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispatchEvent(new WindowEvent(this,WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        CrearProveedor crearProveedor = new CrearProveedor();
        crearProveedor.setVisible(true);
        crearProveedor.setCoordinador(coordinador);
    }//GEN-LAST:event_botonAgregarActionPerformed

    public Coordinador getCoordinador() {
        return coordinador;
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRefrescarTabla;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProveedores;
    // End of variables declaration//GEN-END:variables
}
